image: Visual Studio 2017
clone_folder: c:\projects\json-to-html
configuration: Release

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Cygwin64
      COMPILER: cygwin
      CYGWIN_NOWINPATH: yes
      CYGSH: C:\cygwin64\bin\bash -c
    - platform: Win32
      COMPILER: vs

install:
  - if [%COMPILER%]==[vs] cinst cmake.install ninja
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - if [%COMPILER%]==[vs] call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - if [%COMPILER%]==[cygwin] SET "PATH=C:\cygwin64\bin;C:\cygwin64\usr\bin;%PATH%"
  - if [%COMPILER%]==[cygwin] SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - git submodule -q update --init --recursive
  - cd %WORKSPACE%
  - mkdir cygwin-downloads
  - ps: if($env:COMPILER -eq "cygwin") { Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile $env:WORKSPACE\cygwin-setup.exe }
  - if [%COMPILER%]==[cygwin] %WORKSPACE%\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --root C:\cygwin64 --local-package-dir %WORKSPACE%\cygwin-downloads --packages gcc-g++,cmake,ninja
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - if [%COMPILER%]==[vs] bootstrap-vcpkg.bat
  - if [%COMPILER%]==[vs] vcpkg integrate install
  - cd %WORKSPACE%\json-to-html\
  - mkdir build
  - cd build
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake /cygdrive/c/projects/json-to-html -G "Ninja" -DCMAKE_BUILD_TYPE="Debug"'
  - if [%COMPILER%]==[vs]     cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE="Debug"

build_script:
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake --build .'
  - if [%COMPILER%]==[vs]     cmake --build .
  -
